on: [push, pull_request]
name: edwood

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on
      acmeshell: sh

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run Go tests
      run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

    - name: Upload coverage to codecov
      if: matrix.platform == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash)

    - name: Build with duitdraw on non-windows systems
      if: matrix.platform != 'windows-latest'
      run: go get -tags 'duitdraw mux9p' -t -v ./...

    - name: Run go vet
      run: go vet .

    - name: Install staticcheck and misspell
      run: |
        go get honnef.co/go/tools/cmd/staticcheck@v0.0.1-2020.1.5
        go get github.com/client9/misspell/cmd/misspell@v0.3.4
      working-directory: /

    - name: Run staticcheck and misspell
      run: |
        export PATH=${PATH}:$(go env GOPATH)/bin
        staticcheck -debug.version
        staticcheck -checks inherit,-U1000,-SA4003 ./...
        misspell -error .
      shell: bash

    - name: Check gofmt
      run: diff -u <(echo -n) <(gofmt -d -s .)
      shell: bash
